name: Save OCI Credentials

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  save-oci-credentials:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Write OCI credentials to a JSON file
      - name: Write OCI credentials to file
        run: |
          echo "${{ secrets.OCI_CREDENTIALS_JSON }}" > oci_credentials.json

      # Step 3: Commit and push the JSON file to the main branch
      - name: Commit and push OCI credentials file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add oci_credentials.json
          git commit -m "Add OCI credentials file"
          git push origin main
